"""initial schema

Revision ID: 4ee744b67faf
Revises: 
Create Date: 2026-09-21 13:23:30.806459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee744b67faf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'paused_for_approval', 'completed', 'failed', 'cancelled', name='runstatus'), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('workspace_root', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('final_report', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('available_to_future_runs', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_key'), 'user_preferences', ['key'], unique=True)
    op.create_table('agent_tasks',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'in_progress', 'blocked_on_approval', 'completed', 'failed', 'skipped', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parent_task_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'plan_version', 'sequence_index', name='uq_agent_tasks_run_plan_seq')
    )
    op.create_index('ix_agent_tasks_run_status', 'agent_tasks', ['run_id', 'status'], unique=False)
    op.create_table('agent_events',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Enum('debug', 'info', 'warning', 'error', name='eventseverity'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_events_run_created', 'agent_events', ['run_id', 'created_at'], unique=False)
    op.create_table('approval_requests',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'invalidated', name='approvalstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'task_id', 'payload_hash', name='uq_approval_request_run_task_hash')
    )
    op.create_index('ix_approval_requests_status', 'approval_requests', ['status'], unique=False)
    op.create_table('browser_sessions',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', 'crashed', name='browsersessionstatus'), nullable=False),
    sa.Column('playwright_context_id', sa.String(), nullable=True),
    sa.Column('current_url', sa.String(), nullable=True),
    sa.Column('storage_state_path', sa.String(), nullable=True),
    sa.Column('headless', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('depends_on_task_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency_pair')
    )
    op.create_index('ix_task_dependencies_depends_on_task_id', 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index('ix_task_dependencies_task_id', 'task_dependencies', ['task_id'], unique=False)
    op.create_table('workspace_artifacts',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.Enum('document', 'research_note', 'script', 'report', 'screenshot', 'export', 'other', name='artifacttype'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('created_by_tool', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'relative_path', name='uq_workspace_artifact_run_path')
    )
    op.create_table('tool_executions',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('approval_request_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('started', 'succeeded', 'failed', 'timed_out', 'cancelled', name='toolexecutionstatus'), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'attempt_number', name='uq_tool_execution_task_attempt')
    )
    op.create_index('ix_tool_executions_payload_hash', 'tool_executions', ['payload_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_executions_payload_hash', table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_table('workspace_artifacts')
    op.drop_index('ix_task_dependencies_task_id', table_name='task_dependencies')
    op.drop_index('ix_task_dependencies_depends_on_task_id', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_table('browser_sessions')
    op.drop_index('ix_approval_requests_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_agent_events_run_created', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index('ix_agent_tasks_run_status', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_user_preferences_key'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
